apiVersion: v1
kind: Secret
metadata:
  name: authz-secrets
  namespace: dkms-main-ns
type: Opaque
data:
  DB_URL: REPLACE_ME_BASE64
  JWT_SECRET: REPLACE_ME_BASE64
  DOCKER_HUB_USERNAME: REPLACE_ME_BASE64
  DOCKER_HUB_TOKEN: REPLACE_ME_BASE64
  DOCKER_HUB_EMAIL: REPLACE_ME_BASE64
  DOCKER_HUB_SERVER: REPLACE_ME_BASE64
