apiVersion: v1
kind: Service
metadata:
  name: sdn
  labels: { app.kubernetes.io/name: sdn, app.kubernetes.io/part-of: dkms-rust }
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/name: sdn }
  ports:
    - { name: grpc,    port: 50053, targetPort: grpc }
    - { name: http,    port: 8081,  targetPort: http }
    - { name: metrics, port: 9102,  targetPort: metrics }
