ALTER TABLE "Simulation" ADD COLUMN "sdnIp" TEXT NOT NULL DEFAULT '172.30.0.2';
ALTER TABLE "Simulation" ADD COLUMN "sdnPort" INTEGER NOT NULL DEFAULT 3000;
ALTER TABLE "Simulation" ADD COLUMN "sdnTypeHttp" TEXT NOT NULL DEFAULT 'http';
