# HOJA rama 3. Único vecino: INT-3.
qkc_id       = 33
peer_listen  = "127.0.0.1:7033"
local_listen = "127.0.0.1:7133"
admin_http   = "127.0.0.1:7233"

[[links]]
neighbor_id        = 3
neighbor_peer_addr = "127.0.0.1:7003"
quditto_url        = "http://127.0.0.1:8032"   # qd-3b
key_size_bits      = 1024
