# Intermedio rama 1. Vecinos: HUB (0) y HOJA-11.
qkc_id       = 1
peer_listen  = "127.0.0.1:7001"
local_listen = "127.0.0.1:7101"
admin_http   = "127.0.0.1:7201"

[[links]]
neighbor_id        = 0
neighbor_peer_addr = "127.0.0.1:7000"
quditto_url        = "http://127.0.0.1:8011"   # qd-1a
key_size_bits      = 1024

[[links]]
neighbor_id        = 11
neighbor_peer_addr = "127.0.0.1:7011"
quditto_url        = "http://127.0.0.1:8012"   # qd-1b
key_size_bits      = 1024
