apiVersion: v1
kind: Service
metadata:
  name: quditto
  labels: { app.kubernetes.io/name: quditto, app.kubernetes.io/part-of: dkms-rust }
spec:
  type: ClusterIP
  selector: { app.kubernetes.io/name: quditto }
  ports:
    - { name: grpc,    port: 50055, targetPort: grpc }
    - { name: metrics, port: 9104,  targetPort: metrics }
