#!/usr/bin/env python3
"""Write the landing page of the workspace rustdoc.

`cargo doc --workspace` leaves one directory per crate under `target/doc/`
and no `index.html` at the root, so a published tree opens on a 404. This
writes that root page from `cargo metadata`: one row per workspace package,
with its `description`, split into the runtime modules and the libraries,
plus the extra binaries rustdoc emitted. Run after `cargo doc`:

    scripts/rustdoc-index.py [DOC_DIR]

`DOC_DIR` defaults to `<target_directory>/doc` as cargo reports it, so
`CARGO_TARGET_DIR` is honoured. `make doc` runs it, and the docs workflow
publishes the result.
"""

import html
import json
import pathlib
import subprocess
import sys

MODULES = ["qkc", "orr", "sdn", "dkms", "quditto"]

STYLE = """
:root { color-scheme: light dark; }
body { margin: 0 auto; max-width: 52rem; padding: 2rem 1rem 4rem;
       font: 15px/1.5 system-ui, sans-serif; }
h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
h2 { font-size: 1.05rem; margin: 2rem 0 .5rem; text-transform: uppercase;
     letter-spacing: .04em; opacity: .7; }
p.lead { margin: 0 0 1rem; opacity: .8; }
table { border-collapse: collapse; width: 100%; }
td { padding: .45rem .5rem; vertical-align: top; border-top: 1px solid
     rgba(128,128,128,.25); }
td:first-child { white-space: nowrap; font-family: ui-monospace, monospace; }
a { color: inherit; }
footer { margin-top: 3rem; font-size: .85rem; opacity: .65; }
"""


def metadata():
    out = subprocess.check_output(
        ["cargo", "metadata", "--format-version", "1", "--no-deps"], text=True
    )
    return json.loads(out)


def row(name, desc):
    return (
        f'<tr><td><a href="{html.escape(name)}/index.html">{html.escape(name)}</a></td>'
        f"<td>{html.escape(desc or '')}</td></tr>"
    )


def main(meta, doc_dir):
    packages = {p["name"]: p for p in meta["packages"]}
    # Directory names use underscores; package names may use dashes.
    present = {p.name for p in doc_dir.iterdir() if (p / "index.html").exists()}

    def has(name):
        return name.replace("-", "_") in present

    modules = [
        row(n, packages[n]["description"]) for n in MODULES if n in packages and has(n)
    ]
    libs = [
        row(n, p["description"])
        for n, p in sorted(packages.items())
        if n not in MODULES and has(n)
    ]
    # Binaries that are not a package of their own (test clients, tools).
    listed = {n.replace("-", "_") for n in packages}
    bins = []
    for p in meta["packages"]:
        for t in p["targets"]:
            if "bin" in t["kind"]:
                d = t["name"].replace("-", "_")
                if d in present and d not in listed:
                    bins.append(row(d, f"binary of `{p['name']}`"))
    bins.sort()

    def section(title, rows):
        if not rows:
            return ""
        return f"<h2>{title}</h2><table>{''.join(rows)}</table>"

    page = f"""<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>dkms_rust — rustdoc</title>
<style>{STYLE}</style>
<h1>dkms_rust</h1>
<p class="lead">API reference of the workspace, one entry per crate, private
items included. Design notes, deployment and the trust model live in the
repository's <code>README.md</code> and <code>docs/</code>.</p>
{section("Runtime modules", modules)}
{section("Libraries", libs)}
{section("Other binaries", bins)}
<footer>Generated by <code>scripts/rustdoc-index.py</code> from
<code>cargo metadata</code>.</footer>
"""
    (doc_dir / "index.html").write_text(page)
    print(f"wrote {doc_dir / 'index.html'} ({len(modules)} modules, {len(libs)} libraries, {len(bins)} binaries)")


if __name__ == "__main__":
    meta = metadata()
    if len(sys.argv) > 1:
        target = pathlib.Path(sys.argv[1])
    else:
        target = pathlib.Path(meta["target_directory"]) / "doc"
    if not target.is_dir():
        sys.exit(f"{target}: not a directory — run `cargo doc --workspace` first")
    main(meta, target)
